// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaGI8aEFcuNIqpZzRrLCdr3QYrDPbvbZw',
    appId: '1:586485641496:web:d00910c3b9c4330b08ae6d',
    messagingSenderId: '586485641496',
    projectId: 'attendance-monitoring-798a8',
    authDomain: 'attendance-monitoring-798a8.firebaseapp.com',
    storageBucket: 'attendance-monitoring-798a8.appspot.com',
    measurementId: 'G-SKGR1WP9YG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqoAgUpEaK5WtkbWgfTWHqXvtZpnXLZmY',
    appId: '1:586485641496:android:315b07b6c64f047e08ae6d',
    messagingSenderId: '586485641496',
    projectId: 'attendance-monitoring-798a8',
    storageBucket: 'attendance-monitoring-798a8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVXrDfaZia3jTUz-PVudCThEJLyY1zkFo',
    appId: '1:586485641496:ios:c4340f2665ba834c08ae6d',
    messagingSenderId: '586485641496',
    projectId: 'attendance-monitoring-798a8',
    storageBucket: 'attendance-monitoring-798a8.appspot.com',
    iosBundleId: 'com.example.attendance',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVXrDfaZia3jTUz-PVudCThEJLyY1zkFo',
    appId: '1:586485641496:ios:7d0c40c085cc49da08ae6d',
    messagingSenderId: '586485641496',
    projectId: 'attendance-monitoring-798a8',
    storageBucket: 'attendance-monitoring-798a8.appspot.com',
    iosBundleId: 'com.example.attendance.RunnerTests',
  );
}
